name: Build NextJSs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: /portfolio

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name : Install dependencies & build
        run : |
          npm i
          npm run build-static

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
